Use schema.sql from bdcs.rpm

diff --git a/tests/bin/import-metadata b/tests/bin/import-metadata
--- a/tests/bin/import-metadata
+++ b/tests/bin/import-metadata
@@ -9,7 +9,7 @@ set -e
 
 # needs bdcs.rpm installed
 IMPORT="/usr/libexec/weldr/bdcs-import"
-SCHEMA="./schema.sql"
+SCHEMA=`ls /usr/share/bdcs-*/schema.sql`
 METADATA="metadata.db"
 
 if [ -z "$1" ]; then
@@ -20,7 +20,6 @@ else
     REMOVE_IMPORT_REPO=0
 fi
 
-[ -f "$SCHEMA" ] || curl -o "$SCHEMA" https://raw.githubusercontent.com/weldr/bdcs/master/schema.sql
 sqlite3 "$METADATA" < "$SCHEMA"
 
 DNF_ROOT=`mktemp -d /tmp/dnf.root.XXXXXX`
@@ -41,5 +40,5 @@ for F in $DNF_DOWNLOAD/*.rpm; do
 done
 
 # cleanup temporary directories and files
-rm -rf $DNF_ROOT $DNF_DOWNLOAD $SCHEMA || echo "Can't remove some files"
+rm -rf $DNF_ROOT $DNF_DOWNLOAD || echo "Can't remove some files"
 [ "$REMOVE_IMPORT_REPO" == 1 ] && rm -rf $IMPORT_REPO || echo "Can't remove some files"
