Install bdcs.rpm from Copr instead of pulling it from S3

diff --git a/tests/bin/import-metadata b/tests/bin/import-metadata
--- a/tests/bin/import-metadata
+++ b/tests/bin/import-metadata
@@ -7,7 +7,8 @@ set -e
 # create the MDDB database if it doesn't exist
 # ARG1 - OPTIONAL - a content store directory for exports
 
-IMPORT="./bdcs-import"
+# needs bdcs.rpm installed
+IMPORT="/usr/libexec/weldr/bdcs-import"
 SCHEMA="./schema.sql"
 METADATA="metadata.db"
 
@@ -19,7 +20,6 @@ else
     REMOVE_IMPORT_REPO=0
 fi
 
-[ -f "$IMPORT" ] || curl -o "$IMPORT" https://s3.amazonaws.com/weldr/bdcs-import && chmod a+x "$IMPORT"
 [ -f "$SCHEMA" ] || curl -o "$SCHEMA" https://raw.githubusercontent.com/weldr/bdcs/master/schema.sql
 sqlite3 "$METADATA" < "$SCHEMA"
 
@@ -41,5 +41,5 @@ for F in $DNF_DOWNLOAD/*.rpm; do
 done
 
 # cleanup temporary directories and files
-rm -rf $DNF_ROOT $DNF_DOWNLOAD $IMPORT $SCHEMA || echo "Can't remove some files"
+rm -rf $DNF_ROOT $DNF_DOWNLOAD $SCHEMA || echo "Can't remove some files"
 [ "$REMOVE_IMPORT_REPO" == 1 ] && rm -rf $IMPORT_REPO || echo "Can't remove some files"
